# Generated by Django 5.2.3 on 2025-06-13 00:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FotoImovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='fotos_imoveis/', verbose_name='Foto')),
            ],
        ),
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100, verbose_name='Título do Anúncio')),
                ('descricao', models.TextField(blank=True)),
                ('localizacao', models.CharField(max_length=255)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Preço')),
                ('numero_quartos', models.PositiveIntegerField(verbose_name='Nº de Quartos')),
                ('disponivel', models.BooleanField(default=True, verbose_name='Disponível para Venda')),
                ('tipo_imovel', models.CharField(choices=[('CASA', 'Casa'), ('APARTAMENTO', 'Apartamento'), ('TERRENO', 'Terreno')], max_length=20, verbose_name='Tipo de Imóvel')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
