# Generated by Django 5.2.3 on 2025-06-13 00:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imoveis', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='corretor_responsavel',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo_usuario': 'CORRETOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Corretor Responsável'),
        ),
        migrations.AddField(
            model_name='fotoimovel',
            name='imovel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='imoveis.imovel'),
        ),
    ]
