# Generated by Django 5.2.3 on 2025-06-13 00:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imoveis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('previsao_entrega', models.DateField(verbose_name='Previsão de Entrega')),
                ('status_atual', models.CharField(blank=True, max_length=100, verbose_name='Status Atual')),
                ('imovel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='imoveis.imovel', verbose_name='Imóvel Associado')),
            ],
        ),
        migrations.CreateModel(
            name='StatusObra',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fase', models.CharField(max_length=50, verbose_name='Fase da Obra')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição da Atualização')),
                ('percentual_concluido', models.PositiveIntegerField(verbose_name='Percentual Concluído (%)')),
                ('data_atualizacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Atualização')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_status', to='obras.obra', verbose_name='Obra')),
            ],
            options={
                'verbose_name': 'Status da Obra',
                'verbose_name_plural': 'Status das Obras',
                'ordering': ['-data_atualizacao'],
            },
        ),
    ]
